#helm:generate helm tpl -o $HELM_GENERATE_DIR/manifests/atc-svc.yaml $HELM_GENERATE_DIR/tpl/atc-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: concourse
  labels:
    name: concourse
    role: ci
    environment: dev
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    name: concourse-atc
  - port: 2222
    targetPort: 2222
    name: concourse-tsa
  selector:
    name: concourse
    role: ci
    environment: dev
