#helm:generate helm tpl -o $HELM_GENERATE_DIR/manifests/worker-rc.yaml $HELM_GENERATE_DIR/tpl/worker-rc.yaml
kind: ReplicationController
apiVersion: v1
metadata:
  name: concourse-worker
  labels:
    name: concourse-worker
    environment: dev
    role: ci
    heritage: helm
    provider: concourse-ci
spec:
  replicas: 1
  selector:
    name: concourse-worker
    environment: dev
    role: ci
  template:
    metadata:
      labels:
        name: concourse-worker
        environment: dev
        role: ci
    spec:
      containers:
        - name: concourse-worker
          image: 'jhgaylor/it-ci-worker:latest'
          ports:
            - containerPort: 8080
          env:
            - name: TSA_HOST
              value: '{{env "TSA_HOST" | default "concourse"}}'
            - name: WORK_DIR
              value: '{{env "WORK_DIR" | default "/opt/concourse/worker"}}'

