#helm:generate helm tpl -o $HELM_GENERATE_DIR/manifests/rc.yaml $HELM_GENERATE_DIR/tpl/rc.yaml
kind: ReplicationController
apiVersion: v1
metadata:
  name: postgresql
  labels:
    name: postgresql
    environment: dev
    role: db
    heritage: helm
    provider: postgresql
spec:
  replicas: 1
  selector:
    name: postgresql
    environment: dev
    role: db
  template:
    metadata:
      labels:
        name: postgresql
        environment: dev
        role: db
    spec:
      containers:
        - name: postgresql
          image: postgres
          ports:
            - containerPort: {{env "POSTGRES_PORT" | default "5432"}}
          env:
            - name: POSTGRES_USER
              value: {{env "POSTGRES_USER" | default "ci"}}
            - name: POSTGRES_PASSWORD
              value: {{env "POSTGRES_PASSWORD" | default "ci"}}
            - name: POSTGRES_DB
              value: {{env "POSTGRES_DB" | default "concourse"}}
