#helm:generate helm tpl -o $HELM_GENERATE_DIR/manifests/svc.yaml $HELM_GENERATE_DIR/tpl/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    name: postgresql
    role: db
    environment: dev
    heritage: helm
spec:
  type: LoadBalancer
  ports:
  - port: {{env "POSTGRES_PORT" | default "5432"}}
    targetPort: {{env "POSTGRES_PORT" | default "5432"}}
    name: postgresql-db
  selector:
    name: postgresql
    role: db
    environment: dev
