apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    name: mongo
    role: db
    environment: dev
spec:
  type: LoadBalancer
  ports:
  - port: 27017
    targetPort: 27017
    name: mongo-db
  selector:
    name: mongo
    role: db
    environment: dev
